/**
 * This service describes an interface to access auction data from the CarOnSale API.
 */
export interface ICarOnSaleClient {
  getRunningAuctions(
    filter?: any
  ): Promise<{ items: Auction[]; page: number; total: number }>;
}

export interface Auction {
  id: number;
  label: string;
  endingTime: string;
  state: number;
  minimumRequiredAsk: number;
  currentHighestBidValue: number;
  numBids: number;
  locationAddress: string | null;
  locationCity: string;
  locationZip: string;
  startedAt: string;
  createdAt: string;
  updatedAt: string;
  hotBid: boolean;
  originalMinimumRequiredAsk: number | null;
  allowInstantPurchase: boolean;
  instantPurchasePossibleUntil: string | null;
  advertisementHtmlContent: string | null;
  instantPurchasePrice: number | null;
  locationCountryCode: string;
  startingBidValue: number;
  uuid: string;
  _fk_uuid_vehicle: string;
  _fk_uuid_sellerUser: string;
  _fk_uuid_highestBiddingBuyerUser: string;
  urlToPickupBuyerDocument: string | null;
  paymentProcess: number;
  type: number;
  _fk_uuid_creatingSellerUser: string | null;
  isTest: boolean;
  displayMinAsk: boolean;
  isLive: boolean;
  isTransportationDisabledManually: boolean;
  startingBidValueNet: number;
  minimumRequiredAskNet: number;
  originalMinimumRequiredAskNet: number | null;
  purchasePriceNet: number;
  currentHighestBidValueNet: number;
  highestBidValueAtEndingTimeNet: number | null;
  instantPurchasePriceNet: number | null;
  lastOfferBySellerNet: number | null;
  previousLastOfferBySellerNet: number | null;
  counterOfferByBuyerNet: number | null;
  previousCounterOfferByBuyerNet: number | null;
  renegotiationMidpointValueNet: number | null;
  pickupInstructions: string;
  thirdPartyVATDepositTransferReference: string | null;
  thirdPartyVatTransferReference: string | null;
  thirdPartyVATDepositRefundReference: string | null;
  preventSellerFactoring: boolean;
  listingSurchargeFeeInvoiceReference: string | null;
  additionalTaxType: number;
  additionalTaxValue: number | null;
  isVATReportable: boolean;
  thirdPartyVATDepositReversalReference: string | null;
  uploadMethod: number;
  additionalTaxExportDiscount: number;
  isCosCheckPlusGuaranteeEnabled: boolean;
  isExtendedGuaranteeEnabled: boolean;
  bookedServicesInvoiceReference: string | null;
  directUploadRejectionReasons: string[];
  readyToBeReinsertedSince: string | null;
  externalRenegotiationTicketUuid: string | null;
  urlToCoverLetter: string | null;
  sellerToCosInvoiceUrlFirstUploadedAt: string | null;
  thirdPartyCorrectionInvoiceReference: string | null;
  urlToCorrectionInvoice: string | null;
  reauctionedWaitingForBuyerPaymentAt: string | null;
  _fk_uuid_reauctioningAssignedKAM: string | null;
  _fk_uuid_reauctioningAssignedFSM: string | null;
  isReauction: boolean;
  biddingAgentValue: number;
  didIBidAtLeastOnce: boolean;
  isParked: boolean;
  remainingTimeInSeconds: number;
  remainingTimeForInstantPurchaseInSeconds: number | null;
  associatedVehicle: AssociatedVehicle;
  amIInvolved: boolean;
  amIHighestBidder: boolean;
  sellerContact: null | any;
  rating: null | any;
  isTransportationAllowedForRegion: boolean;
  isExternalPaymentAllowed: boolean;
  remainingDaysUntilReauctioning: null | number;
  remainingDaysUntilLatePickup: null | number;
  latePickupFee: null | any;
  isTransportationBookingPossible: boolean;
  isExpressPickupAvailable: boolean;
  pickupPossibleInDays: null | number;
  sellerAccount: {
    shouldApplyStandingCosts: boolean;
    isCompoundEnabled: boolean;
  };
  amIRegularBuyer: boolean;
  isCrossBorderNetSale: boolean;
  buyerPurchaseFee: number;
  buyerSuccessFee: number;
  vatAmount: number;
  vatRate: number;
  complaintPeriodEndAt: null | any;
  transportBookingPeriodEndAt: null | any;
  isCompoundPickup: boolean;
  hasIncreasedPickupTime: boolean;
  buyerCrossBorderProcessingAmount: number;
  isRecommended: boolean;
  sellerType: number;
  transportationTask: null | any;
  enforceTransportation: boolean;
  isTransportationAvailable: boolean;
  isMinAskReached: boolean;
  isWatching: boolean;
  biddingAgentValueNet: null | any;
  distanceToVehicleInKms: number;
  hasNextAuction: null | any;
  hasPreviousAuction: null | any;
}

type AssociatedVehicle = {
  ac: number;
  ez: string;
  id: number;
  vin: string;
  make: string;
  uuid: string;
  doors: number;
  model: string;
  lastHu: null;
  origin: number;
  numKeys: number;
  sunRoof: number;
  category: number;
  coupling: number;
  euroNorm: string;
  fuelType: number;
  numSeats: number;
  createdAt: string;
  deletedAt: null;
  updatedAt: string;
  dataSource: number;
  externalId: null;
  hasDamages: boolean;
  headlights: number;
  isRollable: boolean;
  navigation: number;
  upholstery: number;
  co2Emission: {
    nedc: number;
    wltp: number;
  };
  hadAccident: boolean;
  mileageInKm: number;
  dataWarnings: number[];
  licensePlate: null;
  numPreOwners: number;
  readyToDrive: number;
  sportPackage: number;
  transmission: number;
  bodyColorCode: number;
  vehicleHeater: number;
  additionalInfo: null;
  huReportExists: boolean;
  sourceLanguage: string;
  commercialUsage: any[];
  datBaseModelRaw: null;
  enginePowerInHp: number;
  engineSizeInCcm: number;
  fuelConsumption: {
    wltp: number;
  };
  hasEndorsements: boolean;
  isIntendedUse01: boolean;
  urlToMotorSound: null;
  vatIdReportable: boolean;
  isVehicleClassN1: boolean;
  urlToAttachment1: null;
  urlToAttachment2: null;
  urlToAttachment3: null;
  huReportAvailable: number;
  isOdometerInMiles: boolean;
  parkingAssistance: number;
  damagesDescription: null;
  dimensionWidthInCm: null;
  hasMaintenanceBook: boolean;
  unloadedWeightInKg: null;
  accidentDescription: null;
  dimensionHeightInCm: null;
  dimensionLengthInCm: null;
  isReimportedVehicle: boolean;
  readyToDriveDetails: string;
  fullServiceHistoryType: number;
  isCocDocumentAvailable: boolean;
  isDataExcerptAvailable: boolean;
  urlsByLanguageToExpose: Record<string, string>;
  fieldsConfirmationStatus: Record<string, any>;
  urlToVehicleSummarySheet: string;
  countryOfLastRegistration: string;
  lastServiceInspectionDate: null;
  serviceHistoryAvailability: number;
  lastServiceInspectionMileage: null;
  damages: any[];
  vehicleImages: {
    url: string;
    perspective: number;
  }[];
  paintState: any[];
  tires: any[];
  technicalState: any[];
  equipmentData: any[];
  equipmentHighlights: any[];
};
